COLUMNS:
  user_id: UUID               
  event_id: UUID               
  organizer_id: UUID           
  is_booked: Int8               
  num_bookings: Int32           
  is_liked: Int8               
  num_likes: Int32             
  is_commented: Int8            
  num_comments: Int32  