COLUMNS:
  ISBN: str
  Book-Title: str
  Book-Author: str
  Year-Of-Publication: Int32
  Publisher: str
  Image-URL-S: str
  Image-URL-M: str
  Image-URL-L: str
  User-ID: Int32
  Book-Rating: Int8
  Age: Int32
  Location: str

