artifacts_root: artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:https://github.com/caserec/Datasets-for-Recommender-Systems/blob/master/Processed%20Datasets/Anime/anime.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
