artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/caserec/Datasets-for-Recommender-Systems/raw/refs/heads/master/Processed%20Datasets/BookCrossing/book_crossing.zip
  source: arashnic/book-recommendation-dataset 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data

data_generation:
  root_dir: artifacts/data_ingestion
  data_dir: artifacts/data_ingestion/generated_data

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/generated_data/merged_interactions.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  merged_data_url: artifacts/data_ingestion/generated_data/merged_interactions.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/generated_data/merged_interactions.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json