artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/caserec/Datasets-for-Recommender-Systems/raw/refs/heads/master/Processed%20Datasets/Steam/steam.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion